name: UniqueInventories
main: no.runsafe.UniqueInventories.Plugin
version: 1.2
authors: [Kruithne, mortenn]
description: Allows multiple inventories across worlds.
commands:
  uniqueinv:
    description: Unique Inventories commands
    usage: /uniqueinv (debug <level>|push|pop|list|template load|template save|worldwipe <world>)
    aliases: [uinv]

permissions:
  uniqueinventories.*:
    description: Gives access to all UniqueInventories commands
    children:
      uniqueinventories.stack: true
      uniqueinventories.debug: true
  uniqueinventories.stack:
    description: Allows players to store and restore their inventory in a stack per world.
    default: false
  uniqueinventories.debug:
    description: Allows the control of debug output.
    default: false
  uniqueinventories.template:
    description: Allows editing the template inventory for a world.
    default: false
  uniqueinventories.worldwipe:
    description: Allows the use of the world-wipe command, erasing all inventories.
    default: false